### ISSUE TITLE
Apply bad words filter before accepting the username

### ISSUE THREAD

**Issue by itaditya** [sdslabs/bot#21]
In the form in which a user is required to enter a username, any word is accepted. I was able to use even bad words (need examples ?) as my username. Then in the chat also bad words are sent to other users. This hinders a chat conversation. Some filter must be provided or else give user a preference to mask bad words in a conversation

**Comment by csoni111** [comment]
@itaditya please be more specific! You may include some description about the issue.

**Comment by csoni111** [comment]
@itaditya I think you posted this issue on the wrong repo. Did you mean to post this on [Jinora](github.com/sdslabs/jinora) _(anonymous chat application)_?

**Comment by itaditya** [comment]
Jinora is giving 404. What's hosted on chat.sdslabs.com

**Comment by csoni111** [comment]
[Jinora](https://github.com/sdslabs/jinora) is hosted on [chat.sdslabs.co](https://chat.sdslabs.co).
